title: EvolGenom IT
description: MTA-ELTE Momentum Evolutionary Genomics Research Group IT documentation
url: "https://drenal.github.io/evolgenom"
#baseurl: "/evolgenom"

permalink: pretty

remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"
search_enabled: true
aux_links:
  "Research Group's Homepage":
    - "https://evolgenom.elte.hu"
  "View on GitHub":
    - "https://github.com/drenal/evolgenom"
