title: EvolGenom IT
description: MTA-ELTE Momentum Evolutionary Genomics Research Group IT documentation
url: "https://drenal.github.io"
baseurl: "/evolgenom"

permalink: pretty

remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark" or nil (default)
color_scheme: "dark"
search_enabled: true
aux_links:
    "Evolutionary Genomics Research Group":
      - "https://evolgenom.elte.hu"
